name: csharp-api

on:
  push:
    branches: main
    paths:
     - apps/csharp-api/*
     - .github/workflows/csharp-api.yml
  pull_request:
    branches: main

jobs:
  push-to-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./apps/csharp-api
          push: true
          tags: ghcr.io/jimpaine/containerapp:csharp-api-0.1.${{ github.RUN_NUMBER }}
  deploy-to-dev:
    environment:
      name: dev
      url: ${{ steps.get-url.outputs.fqdn }}
    runs-on: ubuntu-latest
    needs: push-to-packages
    steps:
      - uses: actions/checkout@v2
      - run: |
          az login --service-principal \
          -u ${{ secrets.AZ_CLI_APP_ID }} \
          -p ${{ secrets.AZ_CLI_PASSWORD }} \
          --tenant ${{ secrets.AZ_CLI_TENANT_ID }}
      - run: az account set -s ${{ secrets.AZ_CLI_SUBSCRIPTION }}
      - run: az provider register --namespace Microsoft.App
      - run: az config set extension.use_dynamic_install=yes_without_prompt
      - run: echo "PREVIOUS_REVISION=$(az containerapp revision list -n csharp-api -g containerapps-qrcpbr3qfrcik | jq 'sort_by(.createdTime) | .[] | .name' | tail -n 1 | sed 's|\"||g')" >> $GITHUB_ENV
      - run: |
          az deployment group create \
          -n 'csharp-api${{ github.RUN_NUMBER }}' \
          -g  ${{ secrets.RESOURCE_GROUP }} \
          -f ./apps/csharp-api/main.bicep \
          -p environmentName=environment image=ghcr.io/jimpaine/containerapp:csharp-api-0.1.${{ github.RUN_NUMBER }} version=0.1.${{ github.RUN_NUMBER }} previous_version=${{ env.PREVIOUS_REVISION }}
      - name: get-url
        id: get-url
        run: echo "::set-output name=fqdn::https://$(az containerapp show -n csharp-api -g ${{ secrets.RESOURCE_GROUP }} --query configuration.ingress.fqdn -o tsv)"
    outputs:
      previousVersion: ${{ env.PREVIOUS_REVISION }}
      currentVersion: 'csharp-api--0-1-${{ github.RUN_NUMBER }}'
  deploy-to-test:
    environment:
      name: test
      url: ${{ steps.get-url.outputs.fqdn }}
    runs-on: ubuntu-latest
    needs: deploy-to-dev
    steps:
      - uses: actions/checkout@v2
      - run: |
          az login --service-principal \
          -u ${{ secrets.AZ_CLI_APP_ID }} \
          -p ${{ secrets.AZ_CLI_PASSWORD }} \
          --tenant ${{ secrets.AZ_CLI_TENANT_ID }}
      - run: az account set -s ${{ secrets.AZ_CLI_SUBSCRIPTION }}
      - run: az provider register --namespace Microsoft.App
      - run: az config set extension.use_dynamic_install=yes_without_prompt
      - run: |
          az containerapp update \
          -n csharp-api -g ${{ secrets.RESOURCE_GROUP }} \
          --traffic-weight '${{ needs.deploy-to-dev.outputs.previousVersion }}=50,${{ needs.deploy-to-dev.outputs.currentVersion }}=50'
      - name: get-url
        id: get-url
        run: echo "::set-output name=fqdn::https://$(az containerapp show -n csharp-api -g ${{ secrets.RESOURCE_GROUP }} --query configuration.ingress.fqdn -o tsv)"
  deploy-to-prod:
    environment:
      name: prod
      url: ${{ steps.get-url.outputs.fqdn }}
    runs-on: ubuntu-latest
    needs: deploy-to-test
    steps:
      - uses: actions/checkout@v2
      - run: |
          az login --service-principal \
          -u ${{ secrets.AZ_CLI_APP_ID }} \
          -p ${{ secrets.AZ_CLI_PASSWORD }} \
          --tenant ${{ secrets.AZ_CLI_TENANT_ID }}
      - run: az account set -s ${{ secrets.AZ_CLI_SUBSCRIPTION }}
      - run: echo "CURRENT_REVISION=$(az containerapp revision list -n csharp-api -g containerapps-qrcpbr3qfrcik | jq 'sort_by(.createdTime) | .[] | .name' | tail -n 1 | sed 's|\"||g')" >> $GITHUB_ENV
      - run: az provider register --namespace Microsoft.App
      - run: az config set extension.use_dynamic_install=yes_without_prompt
      - run: |
          az containerapp update \
          -n csharp-api -g ${{ secrets.RESOURCE_GROUP }} \
          --traffic-weight ${{ env.CURRENT_REVISION }}=100
      - name: get-url
        id: get-url
        run: echo "::set-output name=fqdn::https://$(az containerapp show -n csharp-api -g ${{ secrets.RESOURCE_GROUP }} --query configuration.ingress.fqdn -o tsv)"